### PR TITLE
m: Don't use the borrowing trick under Windows

### PR DESCRIPTION
**Pull request by notgull**
Same as #86 but for Windows instead.

### CODE REVIEW

**Comment by ids1024** [comment]
I assume benchmarking shows no significant impact here either?

**Comment by notgull** [comment]
No, I was going to wait for #86 to merge and then use that benchmark

**Review by ids1024 — APPROVED** [review]
```
running 1 test
test util::tests::test_borrowstack_slice_int ... ignored

test result: ok. 0 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running benches\buffer_mut.rs (target\release\deps\buffer_mut-e9e0e6eee086db28.exe)
buffer_mut()            time:   [772.83 ns 804.35 ns 838.26 ns]
                        change: [-79.144% -78.181% -77.180%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  6 (6.00%) high mild

pixels_mut()            time:   [271.45 ns 281.83 ns 293.28 ns]
                        change: [-4.9890% +0.2741% +5.3843%] (p = 0.92 > 0.05)
                        No change in performance detected.
Found 9 outliers among 100 measurements (9.00%)
  9 (9.00%) high mild
```

If the benchmark result is accurate, this definitely isn't a performance issue.

Everything here looks good.

**Comment by notgull** [comment]
Thanks for saving me a trip to my Windows vm!

**Pull request merged**
