### PR TITLE
Add dependabot support to this repo

### PR DESCRIPTION
**Pull request by notgull**
Helps keep dependencies up to date.

### CODE REVIEW

**Review by john01dav — APPROVED** [review]

**Comment by notgull** [comment]
> I don't know much about the details of dependabot, but this is a useful change. As such, I'm marking my review as positive, but if a review or feedback is wanted on the dependabot configuration it will need to come from someone else. I had it enabled on a previous repository (which seemed to happen automatically), and it sent me emails when it recommended updating. Who gets the emails in this case?

It opens a PR on this repository, so everyone who watches this repo (including me) gets an email.

**Comment by ids1024** [comment]
Might as well do this. I haven't set up dependabot before on anything, but probably should.

**Comment by ids1024** [comment]
Though actually: how exactly does dependabot work with Rust and semver? A library like this doesn't have a `Cargo.lock`. Does it try to update to the latest version and send a PR that may or may not still build successfully on CI?

**Comment by notgull** [comment]
> Though actually: how exactly does dependabot work with Rust and semver? A library like this doesn't have a `Cargo.lock`. Does it try to update to the latest version and send a PR that may or may not still build successfully on CI?

You can see an example of this in #94. It updates to the latest version in the `Cargo.toml` in a PR. From there, CI tests it out.

**Comment by ids1024** [comment]
Okay, so what I expected it to do. Which is useful but won't always work.

**Pull request merged**
